Skip helm v2 init if bootstrap env is passed
rancher/klipper-helm pull request #20
Opened 2020-11-05 22:58 UTC by galal-hussein

https://github.com/rancher/rke2/issues/481

2020-11-05 23:47 UTC, brandond commented
Do we need to throw an error in the Helm Controller if a bootstrap chart asks for helm v2? Seems like just silently disabling tiller for bootstrap charts will cause them to just fail later on with a hard to diagnose error.

2020-11-09 18:19 UTC, brandond requested changes

2020-11-09 18:19 UTC, brandond commented on entry
> +  if [ "$BOOTSTRSP" == "true" ]; then
```suggestion
  if [ "$BOOTSTRAP" == "true" ]; then
```

2020-11-09 20:28 UTC, briandowns approved these changes

2020-11-10 16:16 UTC, brandond approved these changes

2020-11-10 16:16 UTC, merged